# -*- coding: utf-8 -*-
"""
GLM (z.ai) analysis stage of the factor experiment.

Takes the numeric experiment output (results/factor_ic.csv, results/composite.csv) and the
qualitative "Vietnam evidence" claims from the BeeTrade report (Section 5), and asks GLM-4.6
(via the z.ai Anthropic/OpenAI-compatible endpoint) to produce an analytical comparison:
which report claims the live VN100+HNX30 data confirm, contradict, or cannot resolve.

The numeric experiments themselves are pure Python on real market data; this stage uses the
z.ai token for the interpretation / write-up, and its output is folded into the report.

Token: read from $ZAI_TOKEN, else Downloads/tokenclaude.txt, else the literal passed in.
"""
import os, json, ssl, urllib.request
import pandas as pd

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
RESULTS = os.path.join(ROOT, "results")

ZAI_URL = "https://api.z.ai/api/paas/v4/chat/completions"
MODEL = "glm-4.6"


def get_token():
    t = os.environ.get("ZAI_TOKEN")
    if t:
        return t.strip()
    p = os.path.expanduser("~/Downloads/tokenclaude.txt")
    if os.path.exists(p):
        with open(p) as f:
            return f.readline().strip()
    raise SystemExit("No z.ai token found (set $ZAI_TOKEN or ~/Downloads/tokenclaude.txt)")


REPORT_CLAIMS = """\
BeeTrade report (June 2026) -- key Vietnam-evidence claims (Section 5 + family notes):
1. Operating profitability (OP) is the STRONGEST profitability proxy and the primary quality input,
   stronger than ROE/gross profitability.
2. Value is real but contested; HML/value non-redundant, concentrated in financials/real estate,
   must be sector-neutralised and paired with quality.
3. Short-term 1-month reversal (REV) is one of the MOST ROBUST signals; decays by ~2 months.
4. Cross-sectional 12-1 price momentum (MOM) is WEAK / regime-dependent (works mainly after up-markets).
5. Size effect is WEAK; liquidity/illiquidity (Amihud) is MUTED or INVERTED -- foreign capital crowds
   into liquid names, so illiquid small caps do NOT reliably outperform. Treat liquidity as a control.
6. Low-risk family (low IVOL, low beta, low MAX/lottery) generally works; MAX strong but price-limit censored.
7. Asset growth (CMA, low) and low leverage are defensive value-adds.
"""

PROMPT_TMPL = """You are a quantitative equity researcher. Below are (A) the qualitative claims from a
Vietnam equity factor report, and (B) the EMPIRICAL results from an independent replication on live
VN100+HNX30 data (monthly rebalanced, sector+size neutralised, signed so that a POSITIVE mean rank IC
means "the factor works in the direction the report expects"). t-stat |t|>1.96 is significant.

(A) {claims}

(B) Empirical factor results (one row per factor):
{factor_table}

(B2) Family + composite results:
{composite_table}

Write a concise, rigorous markdown analysis (~500-700 words) with these sections:
## Headline findings
## Claim-by-claim verdict
A markdown table: | Report claim | Empirical verdict (Confirmed / Contradicted / Inconclusive) | Evidence (cite the IC / spread numbers) |
## Caveats
Note the short sample, thin universe (~130 liquid names), no short side, and price-limit censoring.
Be honest where the data is too thin to resolve a claim. Do not invent numbers; only use the tables."""


def call_glm(prompt, token, max_tokens=2200):
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    body = json.dumps({
        "model": MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2,
        "max_tokens": max_tokens,
    }).encode()
    req = urllib.request.Request(ZAI_URL, data=body, headers={
        "Authorization": "Bearer " + token, "Content-Type": "application/json"})
    r = urllib.request.urlopen(req, timeout=120, context=ctx)
    return json.load(r)["choices"][0]["message"]["content"]


def main():
    token = get_token()
    fac = pd.read_csv(os.path.join(RESULTS, "factor_ic.csv"))
    comp = pd.read_csv(os.path.join(RESULTS, "composite.csv"))
    prompt = PROMPT_TMPL.format(
        claims=REPORT_CLAIMS,
        factor_table=fac.round(4).to_csv(index=False),
        composite_table=comp.round(4).to_csv(index=False),
    )
    print(f"Calling GLM-4.6 via z.ai ({len(prompt)} char prompt)...")
    out = call_glm(prompt, token)
    path = os.path.join(RESULTS, "zai_analysis.md")
    with open(path, "w") as f:
        f.write("<!-- Generated by GLM-4.6 via z.ai from the empirical factor results -->\n\n")
        f.write(out)
    print(f"Saved GLM analysis -> {path}\n")
    print(out[:1500])


if __name__ == "__main__":
    main()
